### ISSUE TITLE
Icons called with complex names not working

### ISSUE THREAD

**Issue by johnareid54** [galonsos/line_icons#21]
I am having a problem calling the icons by name.
For example:
**Icon(LineIcons.byName('home'));**  works
**Icon(LineIcons.byName('info-circle'));**  does not works

It seems to be related to the name having more than one word in the string.

Any suggestions?

**Comment by galonsos** [comment]
Hi, @johnareid54.

Yes, it does indeed have to do with the number of words of the icon name. Since version 2.0, names are camelCase instead of the original ones. 

So 

`Icon(LineIcons.byName('infoCircle'));`

should work properly.

Out of curiosity, why such a long statement instead of `LineIcon.infoCircle()`?

Thanks.

**Comment by johnareid54** [comment]
Thanks for the great answer!

_Out of curiosity, why such a long statement instead of LineIcon.infoCircle()?_
I guess I did not read the documentation all that well.

**Comment by galonsos** [comment]
You're welcome!

I'd suggest to take a look to the `values` property, which will provide you with a list of the available names. 

Cheers
