### ISSUE TITLE
flutter doesnt recognise version 1.1.0

### ISSUE THREAD

**Issue by ajonno** [galonsos/line_icons#8]
getting this error:

```...depends on line_icons ^1.1.0 which doesn't match any versions...```

**Comment by gavzla** [comment]
@ajonno I see nobody has answer you! If you haven't solve this already and since the developer haven't updated the package in pub.dev, the work around is to put the dependency as follows...

![code](https://user-images.githubusercontent.com/11657368/76920940-bf2ef780-689a-11ea-8f6b-fe1458270b6f.png)

Greetings!

**Comment by ajonno** [comment]
Ah great to know - many thanks!

**Comment by RosalieWessels** [comment]
Hi, 
I was having an issue with where I wasn't able to use the latest icons (I needed a DNA icon). The icon was showing on the website of possible icons but I wasn't able to use it in my code. By using the suggestion @gavzla made, it was able to use it! 
Thank you!

**Comment by galonsos** [comment]
Hi everyone. Sorry for the late late late response. Please, upgrade to version 1.3.2, which I just posted in pub.dev (https://pub.dev/packages/line_icons). But be aware: it has major changes, such as naming. Hope you like it!
